// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ikbywydyidnkohbdrqdk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlrYnl3eWR5aWRua29oYmRycWRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NTMzMzMsImV4cCI6MjA3MDQyOTMzM30.sGaXI3tU9mJgkttF3Xj9KPJchLCtXuIuXUPaP3l8VdY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});